#include "TF47Modules\TF47ServicePoint\TF47ServicePointMacros.hpp"

tf47_modules_sp_markers = ["marker_sp"];

SERVICEPOINT_LOADOUT_CONFIG_BEGIN

SERVICEPOINT_LOADOUT_NAME("Basic Loadout")
SERVICEPOINT_LOADOUT_IS_MODULE(FALSE)
SERVICEPOINT_LOADOUT_ADD_ITEM("arifle_MXC_Holo_pointer_F",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("30Rnd_65x39_caseless_mag",10)
SERVICEPOINT_LOADOUT_ADD_ITEM("FirstAidKit",2)
SERVICEPOINT_LOADOUT_END

SERVICEPOINT_LOADOUT_NAME("Basic Module")
SERVICEPOINT_LOADOUT_IS_MODULE(TRUE)
SERVICEPOINT_LOADOUT_ADD_ITEM("FirstAidKit",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("Medikit",1)
SERVICEPOINT_LOADOUT_END

SERVICEPOINT_LOADOUT_CONFIG_END


SERVICEPOINT_ACE_LOADOUT_CONFIG_BEGIN

SERVICEPOINT_LOADOUT_NAME("Wheels")
SERVICEPOINT_LOADOUT_IS_MODULE(FALSE)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_Wheel",2)
SERVICEPOINT_LOADOUT_END

SERVICEPOINT_LOADOUT_NAME("Tracks")
SERVICEPOINT_LOADOUT_IS_MODULE(TRUE)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_Track",2)
SERVICEPOINT_LOADOUT_END

SERVICEPOINT_ACE_LOADOUT_CONFIG_END
